close all;
cpu=load("cpu.txt");
gpu = load("gpu.txt");
gpu1 = load("gpu1.txt");
gpu2 = load("gpu2.txt");
h=zeros(4,1);
hstring={"CPU总时间","GPU运算时间","GPU内存操作时间","GPU总时间"};
figure();
h(1) = plot(cpu(:,1),cpu(:,2),"r-s","LineWidth",2);
hold on;
h(2)=plot(gpu(:,1),gpu(:,2),"k--*","LineWidth",2);
hold on;
h(3)=plot(gpu1(:,1),gpu1(:,2),"g--^","LineWidth",2);
hold on;
h(4)=plot(gpu2(:,1),gpu2(:,2),"b-s","LineWidth",2);
xlabel("ray num");
ylabel("time/ms");
legend(h,hstring);
set(gca,'fontsize',24);
grid on;